<?php
/**
 * @OA\Post(
 *      path="/oauth/request-for-otp",
 *      tags={AUTHENTICATION_TAG},
 *      summary="Request for OTP",
 *      operationId="sendOTP",
 *      @OA\RequestBody(
 *         @OA\MediaType(
 *             mediaType="application/x-www-form-urlencoded",
 *             @OA\Schema(
 *                 required={"vISDCode","vMobileNumber"},
 *                 @OA\Property(property="vISDCode", type="string"),
 *                 @OA\Property(property="vMobileNumber", type="string")
 *             )
 *         )
 *      ),
 *      @OA\Response(
 *         response=200,
 *         description="4-digit code sent successfully.",
 *         @OA\JsonContent(ref="#/components/schemas/CommonFields"),
 *      ),
 *      @OA\Response(
 *         response=400,
 *         description="Error",
 *         @OA\JsonContent(ref="#/components/schemas/CommonFields"),
 *      )
 * )
 */

 /**
 * @OA\Post(
 *      path="/oauth/verify-otp",
 *      tags={AUTHENTICATION_TAG},
 *      summary="Verify OTP",
 *      operationId="verifyOTP",
 *      @OA\RequestBody(
 *         @OA\MediaType(
 *             mediaType="application/x-www-form-urlencoded",
 *             @OA\Schema(
 *                 required={"vISDCode","vMobileNumber","iOTP"},
 *                 @OA\Property(property="vISDCode", type="string"),
 *                 @OA\Property(property="vMobileNumber", type="string"),
 *                 @OA\Property(property="iOTP", type="integer"),
 *             )
 *         )
 *      ),
 *      @OA\Response(
 *         response=200,
 *         description="OTP has been verified successfully.",
 *         @OA\JsonContent(ref="#/components/schemas/UserResponse"),
 *      ),
 *      @OA\Response(
 *         response=400,
 *         description="Error",
 *         @OA\JsonContent(ref="#/components/schemas/CommonFields"),
 *      )
 * )
 */

/**
 * @OA\Schema(
 *   schema="UserResponse",
 *   type="object",
 *   allOf={
 *     @OA\Schema(ref="#/components/schemas/CommonFields"),
 *     @OA\Schema(
 *          @OA\Property(
 *              property="responseData",
 *              type="object",
 *              ref="#/components/schemas/UserResponseFields"
 *          )
 *      )
 *   }
 * )
*/


/**
 * @OA\Schema(
 *   schema="UserResponseFields",
 *   type="object",
 *   @OA\Property(
 *      property="vSocialId",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="vAccessToken",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="iUserId",
 *      type="integer"
 *   ),
 *   @OA\Property(
 *      property="vFirstName",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="vLastName",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="vISDCode",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="vMobileNumber",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="vEmailId",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="dbLatitude",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="dbLongitude",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="tiIsPremiumUser",
 *      type="integer"
 *   ),
 *   @OA\Property(
 *      property="tiIsSocialLogin",
 *      type="integer"
 *   ),
 *   @OA\Property(
 *      property="tiIsMobileVerified",
 *      type="integer"
 *   ),
 *   @OA\Property(
 *      property="tiGender",
 *      type="integer"
 *   ),
 *   @OA\Property(
 *      property="tiLookingFor",
 *      type="integer"
 *   ),
 *   @OA\Property(
 *      property="iDob",
 *      type="integer"
 *   ),
 *   @OA\Property(
 *      property="vZodiacSignName",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="vOriginCountry",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="vEthnicGroup",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="vEducationQualification",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="vLivingCountry",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="txAboutYourSelf",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="txDealBreaker",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="vCity",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="vFaith",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="tiRelationshipStatus",
 *      type="integer"
 *   ),
 *   @OA\Property(
 *      property="vProfileImage",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="vSelfieImage",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="vVideo",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="vQuickBloxUserId",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="vQbLogin",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="vQbPassword",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="tiIsProfileImageVerified",
 *      type="integer"
 *   ),
 *   @OA\Property(
 *      property="tiIsDrink",
 *      type="integer"
 *   ),
 *   @OA\Property(
 *      property="tiUseDrugs",
 *      type="integer"
 *   ),
 *   @OA\Property(
 *      property="tiBelieveInMarriage",
 *      type="integer"
 *   ),
 *   @OA\Property(
 *      property="tiHaveKids",
 *      type="integer"
 *   ),
 *   @OA\Property(
 *      property="tiSameEthnicity",
 *      type="integer"
 *   ),
 *   @OA\Property(
 *      property="tiSameNationality",
 *      type="integer"
 *   ),
 *   @OA\Property(
 *      property="vOccupation",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="vEarnings",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="vPreferredEarnings",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="tiIsDrinkingPreferred",
 *      type="integer"
 *   ),
 *   @OA\Property(
 *      property="tiIsDrugPreferred",
 *      type="integer"
 *   ),
 *   @OA\Property(
 *      property="tiPreferredPreviouslyMarried",
 *      type="integer"
 *   ),
 *   @OA\Property(
 *      property="tiLikeToHaveKids",
 *      type="integer"
 *   ),
 *   @OA\Property(
 *      property="tiPreferredEducation",
 *      type="integer"
 *   ),
 *   @OA\Property(
 *      property="vPreferredEducation",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="tiPreferredAge",
 *      type="integer"
 *   ),
 *   @OA\Property(
 *      property="tiPreferredReligiousBeliefs",
 *      type="integer"
 *   ),
 *   @OA\Property(
 *      property="tiIsProfileCompleted",
 *      type="integer"
 *   ),
 *   @OA\Property(
 *      property="userLoveLanguages",
 *      type="array",
 *      @OA\Items(ref="#/components/schemas/UserLoveLanguagesResponseFields")
 *   ),
 *   @OA\Property(
 *      property="userFunInterests",
 *      type="array",
 *      @OA\Items(ref="#/components/schemas/UserFunInterestsResponseFields")
 *   ),
 *   @OA\Property(
 *      property="userImages",
 *      type="array",
 *      @OA\Items(ref="#/components/schemas/UserImagesResponseFields")
 *   ),
 *   @OA\Property(
 *      property="tsCreatedAt",
 *      type="string"
 *   ),
 *   @OA\Property(
 *      property="tiIsAdminApproved",
 *      type="integer"
 *   ),
 * )
 */

/**
 * @OA\Schema(
 *   schema="UserLoveLanguagesResponseFields",
 *   @OA\Property(
 *       property="iLoveLanguageId",
 *       type="integer"
 *   ),
 *   @OA\Property(
 *       property="vLoveLanguage",
 *       type="string"
 *   ),
 *    @OA\Property(
 *       property="vLoveLanguageLogo",
 *       type="string"
 *   )
 * )
 */

 /**
 * @OA\Schema(
 *   schema="UserFunInterestsResponseFields",
 *   @OA\Property(
 *       property="iInterestId",
 *       type="integer"
 *   ),
 *   @OA\Property(
 *       property="vInterestName",
 *       type="string"
 *   ),
 *   @OA\Property(
 *       property="vInterestLogo",
 *       type="string"
 *   )
 * )
 */

 /**
 * @OA\Schema(
 *   schema="UserImagesResponseFields",
 *   @OA\Property(
 *       property="iImageId",
 *       type="integer"
 *   ),
 *   @OA\Property(
 *       property="vImageName",
 *       type="string"
 *   )
 * )
 */

