version: '3.9'

networks:
    app-network:
        driver: bridge

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-network    

  laravel:
    build: 
     context: .
     dockerfile: Dockerfile
    container_name: basecode
    depends_on:
      - mysql
    command: bash -c "/wait && a2enmod rewrite && apachectl -D FOREGROUND" 
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html/laravel_basecode/
    environment:
      - WAIT_HOSTS=mysql:3306
    networks:
      - app-network  
      
      
#&& php artisan migrate && php artisan db:seed && php artisan key:generate 